# Generated by Django 4.2.2 on 2023-06-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('product_title', models.CharField(max_length=50, null=True)),
                ('product_category', models.CharField(max_length=50, null=True)),
                ('product_description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('qty', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.register')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
