# Generated by Django 4.2.2 on 2023-06-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
